name: Build Jusu AI APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 31
      ANDROID_BUILD_TOOLS: 31.0.0
      ANDROID_NDK_VERSION: 23.1.7779620

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git openjdk-17-jdk zip unzip libgl1-mesa-dev libgles2-mesa-dev libmtdev-dev libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install --upgrade buildozer cython

      - name: Build APK
        run: |
          buildozer android debug
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: jusu-ai-apk
          path: bin/*.apk
