name: Build Jusu AI APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libmtdev-dev \
            libffi-dev \
            libssl-dev \
            libjpeg-dev \
            build-essential \
            cmake

          pip install --upgrade pip
          pip install --user Cython==0.29.36
          pip install --user buildozer

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: jusu-ai-apk
          path: bin/*.apk
