name: Build JUSU AI Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-setuptools \
          python3-venv \
          unzip \
          zip \
          openjdk-11-jdk \
          wget \
          curl

    - name: Download and install Android SDK command-line tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        rm cmdline-tools.zip

    - name: Set ANDROID_HOME and update PATH
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept licenses and install SDK components
      run: |
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653" "cmake;3.22.1"

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer cython

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

