name: Android Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/.android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
      SDK_ROOT: ${{ github.workspace }}/.android-sdk

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-11-jdk unzip wget
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Download Android command line tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

      - name: Install Android SDK packages
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.0"

      - name: Accept licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Ensure licenses directory exists and populate
        run: |
          mkdir -p $ANDROID_HOME/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_HOME/licenses/intel-android-extra-license

      - name: List licenses
        run: |
          ls -l $ANDROID_HOME/licenses
          cat $ANDROID_HOME/licenses/*

      - name: Build APK
        run: |
          buildozer android debug

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: JusuAI-APK
          path: bin/*.apk
